# ruff: noqa: E402, F401
from .approval import ApprovalBroker, PendingApproval
from .autonomous import AutonomousLimits, AutonomousRunner, RecoveryDecision

"""agent-core — modular foundation for a personal autonomous AI agent.

Phase 0 (IMPLEMENTED): task state model, model-driven planner, executor,
tool system with registry and JSON-Schema validation, permission manager
(LOW/MEDIUM/HIGH, fail-safe approvals), structured event bus, vendor-neutral
ModelProvider interface with a deterministic mock, and one demo tool that
proves the end-to-end flow.

Phase 1 (IMPLEMENTED): model gateway (error normalization + safe retry),
configuration-driven provider selection, and a real OpenAI provider adapter
(optional ``openai`` extra, lazy SDK import).

Phase 2 (IMPLEMENTED): the tool runtime (permission-gated, schema-validated,
metadata-carrying tool execution with structured lifecycle events) and a set
of safe, deterministic built-in tools (calculator, date/time, text utils,
JSON utils).

Phase 3 (IMPLEMENTED): a safe, provider-agnostic filesystem/workspace tool
layer. Nine tools (list_directory, read_text_file, write_text_file,
create_directory, copy_file, move_file, delete_file, file_info,
search_files) operate strictly inside an explicitly configured workspace
boundary enforced by :class:`agent_core.workspace.Workspace`. There is still
NO unrestricted shell/subprocess or arbitrary code execution.

Phase 4 (IMPLEMENTED): document processing & knowledge foundation. Six
formats (TXT, Markdown, PDF, DOCX, PPTX, XLSX) parse — via mature libraries
isolated behind the ``DocumentParser`` interface — into a normalized,
deterministic document model; documents chunk deterministically; and a
provider-neutral :class:`agent_core.documents.KnowledgeStore` performs
lexical retrieval. Four tools (inspect_document, extract_document,
index_document, search_documents) are permission-gated and read only through
the Phase 3 workspace boundary. Document content is untrusted DATA, never
instructions.

Phase 5 (IMPLEMENTED): memory & RAG foundation. A strongly typed,
provider-neutral ``Memory`` model (types, provenance, TTL, soft-delete)
behind the ``MemoryStore`` protocol (``InMemoryMemoryStore``), five
permission-gated memory tools (remember MEDIUM, update_memory MEDIUM,
forget HIGH, recall LOW, list_memories LOW), deterministic lexical memory
retrieval behind the ``MemoryRetriever`` protocol, and a provider-neutral
``ContextBuilder`` (RAG) that combines memories + document chunks into a
structured, bounded, provenance-labeled context. Memory creation is
explicit (never automatic); retrieved memory and document content are
untrusted DATA. Retrieval is lexical only — no embeddings in this phase.

Phase 6 (IMPLEMENTED): a provider-neutral computer foundation with bounded
observations, an optional Windows UI Automation provider, explicit low/medium
primitive tools, permission enforcement, event redaction, deterministic
postcondition verification, timeouts, and bounded idempotent recovery. It is
not unrestricted autonomous computer control. Phase 7 (IMPLEMENTED) adds
same-path ephemeral local pixel-only screenshot observation and verification;
it does not add OCR or semantic vision. Phase 8 (IMPLEMENTED) adds a
provider-neutral voice transport foundation with bounded ephemeral audio,
local deterministic mocks, and a same-`Agent.run` input path; real microphone
capture and external STT/TTS remain NOT IMPLEMENTED. Browser automation,
media generation, semantic/vector retrieval, durable memory, UI, and document
creation remain PLANNED — see ARCHITECTURE.md and ROADMAP.md.
Phase 10 Step 1 adds bounded coding data contracts and a local mock only;
it does not add writes or execution.
"""

from .agent import Agent
from .browser import (
    BROWSER_TOOL_NAMES,
    BrowserActionResult,
    BrowserActionType,
    BrowserBoundingBox,
    BrowserClosePageRequest,
    BrowserCloseSessionRequest,
    BrowserCreatePageRequest,
    BrowserElement,
    BrowserElementRequest,
    BrowserError,
    BrowserFillRequest,
    BrowserFindElementsRequest,
    BrowserHistoryRequest,
    BrowserKey,
    BrowserLimitError,
    BrowserLimits,
    BrowserNavigateRequest,
    BrowserObservation,
    BrowserOpenSessionRequest,
    BrowserPage,
    BrowserPageRef,
    BrowserPageSnapshot,
    BrowserPageStatus,
    BrowserPermissionError,
    BrowserPressKeyRequest,
    BrowserProvider,
    BrowserProviderError,
    BrowserProviderUnavailableError,
    BrowserReadyState,
    BrowserRecoveryAction,
    BrowserRecoveryPolicy,
    BrowserRecoveryResult,
    BrowserRuntime,
    BrowserScreenshotMetadata,
    BrowserSelectRequest,
    BrowserSession,
    BrowserSessionStatus,
    BrowserTimeoutError,
    BrowserValidationError,
    BrowserVerificationResult,
    BrowserVerificationStatus,
    BrowserWaitRequest,
    BrowserWaitState,
    BrowserWaitUntil,
    MockBrowserProvider,
    MockElementDefinition,
    PlaywrightBrowserProvider,
    register_browser_tools,
)
from .builtin_tools import (
    CalculatorTool,
    DateTimeTool,
    JsonUtilsTool,
    TextUtilsTool,
    register_default_tools,
)
from .coding import (
    AnalyzedCodeFile,
    CodeAnalysisLimitReason,
    CodeAnalysisMethod,
    CodeAnalysisRequest,
    CodeAnalysisResult,
    CodeAnalysisStatus,
    CodeChange,
    CodeDiagnostic,
    CodeDiagnosticBatch,
    CodeDiagnosticCategory,
    CodeDiagnosticsEngine,
    CodeEditRequest,
    CodeEditResult,
    CodeEditStatus,
    CodeFile,
    CodeFileMetric,
    CodeLanguage,
    CodePatch,
    CodeRegion,
    CodeSkipReason,
    CodeSymbol,
    CodeSymbolKind,
    CodeTestPlanRequest,
    CodeTestPlanResult,
    CodeTestPlanStatus,
    CodingAnalysisRuntime,
    CodingError,
    CodingLimitError,
    CodingLimits,
    CodingObservation,
    CodingOperation,
    CodingPermissionError,
    CodingProject,
    CodingProvider,
    CodingProviderError,
    CodingService,
    CodingTimeoutError,
    CodingUnsupportedOperationError,
    CodingValidationError,
    CodingWorkspaceError,
    DiagnosticSeverity,
    MockCodingProvider,
    ObservedCodeFile,
    PatchCheckStatus,
    PatchValidationCheck,
    PatchValidationMetadata,
    PatchValidationStatus,
    SkippedCodeFile,
    TestCasePlan,
    register_coding_tools,
)
from .computer import (
    HARD_MAX_SCREENSHOT_BYTES,
    HARD_MAX_TEXT_INPUT_CHARS,
    Bounds,
    ComputerActionResult,
    ComputerActionStatus,
    ComputerError,
    ComputerLimits,
    ComputerObservation,
    ComputerOperationResult,
    ComputerProvider,
    ComputerProviderError,
    ComputerRuntime,
    ComputerValidationError,
    FocusWindowAction,
    KeyboardAction,
    KeyboardActionKind,
    KeyboardKey,
    KeyboardModifier,
    MouseAction,
    MouseActionKind,
    MouseButton,
    Point,
    ProviderUnavailableError,
    RecoveryAction,
    RecoveryPolicy,
    RecoveryRecommendation,
    ScreenInfo,
    ScreenshotObservation,
    SelectUIElementAction,
    UIElement,
    UnsupportedPlatformError,
    VerificationCondition,
    VerificationKind,
    VerificationResult,
    VerificationStatus,
    WindowInfo,
    WindowsComputerProvider,
    classify_computer_operation,
    verify_condition,
)
from .computer_tools import (
    COMPUTER_TOOL_NAMES,
    ComputerActiveWindowTool,
    ComputerClickTool,
    ComputerCursorPositionTool,
    ComputerDoubleClickTool,
    ComputerFocusWindowTool,
    ComputerHotkeyTool,
    ComputerInspectUITool,
    ComputerListWindowsTool,
    ComputerMoveMouseTool,
    ComputerPressKeyTool,
    ComputerScreenInfoTool,
    ComputerScreenshotTool,
    ComputerSelectUIElementTool,
    ComputerTypeTextTool,
    register_computer_tools,
)
from .config import Settings
from .demo_tools import DEMO_TOOL_NAME, DemoTool
from .document_tools import (
    DOCUMENT_TOOL_NAMES,
    ExtractDocumentTool,
    IndexDocumentTool,
    InspectDocumentTool,
    SearchDocumentsTool,
    register_document_tools,
)
from .documents import (
    Document,
    DocumentChunk,
    DocumentError,
    DocumentLimits,
    DocumentSection,
    KnowledgeStore,
    RetrievalIndex,
)
from .errors import (
    AgentCoreError,
    PermissionDeniedError,
    PlanningError,
    ProviderConfigurationError,
    ProviderError,
    TaskStateError,
    ToolAlreadyRegisteredError,
    ToolExecutionError,
    ToolInputError,
    ToolNotFoundError,
    TransientProviderError,
)
from .events import AgentEvent, EventBus, EventType, bounded_text, bounded_value, utc_now
from .executor import BasicVerifier, Executor, Verifier, VerifyResult
from .memory import (
    InMemoryMemoryStore,
    LexicalMemoryRetriever,
    Memory,
    MemoryLimits,
    MemoryRetriever,
    MemoryStore,
    MemoryStoreError,
    MemoryType,
    SourceCategory,
    SQLiteMemoryStore,
    make_memory_id,
    metadata_size_bytes,
)
from .memory_tools import (
    MEMORY_TOOL_NAMES,
    ForgetTool,
    ListMemoriesTool,
    RecallTool,
    RememberTool,
    UpdateMemoryTool,
    register_memory_tools,
)
from .permissions import (
    ApprovalCallback,
    ApprovalRequest,
    PermissionDecision,
    PermissionLevel,
    PermissionManager,
    PermissionPolicy,
    ToolDescriptor,
)
from .planner import ModelPlanner, Plan, Planner, PlanStep, plan_json_schema
from .providers import (
    SUPPORTED_PROVIDERS,
    Capability,
    ChatMessage,
    MockModelProvider,
    ModelGateway,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    OpenAIProvider,
    build_gateway,
    create_provider,
)
from .rag.context import Context, ContextBuilder, ContextItem, ContextRequest
from .schema import validate_against_schema
from .tasks import StepStatus, Task, TaskState, TaskStep
from .tool_runtime import ToolInvocation, ToolRuntime
from .tools import Tool, ToolRegistry, ToolResult, ToolSpec
from .vision import (
    BoundingBox,
    ComparisonLimitError,
    DeterministicVisionProvider,
    ImageLimitError,
    ImageSize,
    InvalidImageError,
    InvalidRegionError,
    OptionalImageSupportError,
    RegionSource,
    VisionComparisonError,
    VisionError,
    VisionLimits,
    VisionProvider,
    VisionProviderError,
    VisionTimeoutError,
    VisualAnalysis,
    VisualMatch,
    VisualMatchStatus,
    VisualObservation,
    VisualRegion,
    VisualVerificationCondition,
    VisualVerificationKind,
    VisualVerificationResult,
    VisualVerificationStatus,
    VisualVerifier,
)
from .vision.runtime import VisionRuntime
from .vision.tools import (
    VISION_ANALYZE_SCREENSHOT_TOOL_NAME,
    VISION_TOOL_NAMES,
    VisionAnalyzeScreenshotTool,
    register_vision_tools,
)
from .voice import (
    VOICE_NORMALIZE_TOOL_NAME,
    VOICE_TOOL_NAMES,
    AgentHandoff,
    AudioEncoding,
    AudioFormat,
    AudioInput,
    AudioMetadata,
    MockSTTProvider,
    MockTTSProvider,
    STTProvider,
    SynthesisRequest,
    SynthesisResult,
    TranscriptionResult,
    TranscriptionStatus,
    TTSProvider,
    VoiceError,
    VoiceLimitError,
    VoiceLimits,
    VoiceNormalizeTool,
    VoiceObservation,
    VoiceProviderError,
    VoiceResponse,
    VoiceResponseStatus,
    VoiceRuntime,
    VoiceTimeoutError,
    VoiceValidationError,
    normalize_transcription_text,
    register_voice_tools,
)
from .workspace import Workspace, WorkspaceError, WorkspaceLimits
from .workspace_tools import (
    CopyFileTool,
    CreateDirectoryTool,
    DeleteFileTool,
    FileInfoTool,
    ListDirectoryTool,
    MoveFileTool,
    ReadTextFileTool,
    SearchFilesTool,
    WriteTextFileTool,
    register_workspace_tools,
)

__version__ = "0.9.0"

__all__ = [
    "BROWSER_TOOL_NAMES",
    "COMPUTER_TOOL_NAMES",
    "DEMO_TOOL_NAME",
    "DOCUMENT_TOOL_NAMES",
    "FORGET_TOOL_NAME",
    "HARD_MAX_SCREENSHOT_BYTES",
    "HARD_MAX_TEXT_INPUT_CHARS",
    "LIST_MEMORIES_TOOL_NAME",
    "MEMORY_TOOL_NAMES",
    "RECALL_TOOL_NAME",
    "REMEMBER_TOOL_NAME",
    "SUPPORTED_PROVIDERS",
    "UPDATE_MEMORY_TOOL_NAME",
    "VISION_ANALYZE_SCREENSHOT_TOOL_NAME",
    "VISION_TOOL_NAMES",
    "VOICE_NORMALIZE_TOOL_NAME",
    "VOICE_TOOL_NAMES",
    "Agent",
    "AgentCoreError",
    "AgentEvent",
    "AgentHandoff",
    "AnalyzedCodeFile",
    "ApprovalCallback",
    "ApprovalRequest",
    "AudioEncoding",
    "AudioFormat",
    "AudioInput",
    "AudioMetadata",
    "BasicVerifier",
    "BoundingBox",
    "Bounds",
    "BrowserActionResult",
    "BrowserActionType",
    "BrowserBoundingBox",
    "BrowserClosePageRequest",
    "BrowserCloseSessionRequest",
    "BrowserCreatePageRequest",
    "BrowserElement",
    "BrowserElementRequest",
    "BrowserError",
    "BrowserFillRequest",
    "BrowserFindElementsRequest",
    "BrowserHistoryRequest",
    "BrowserKey",
    "BrowserLimitError",
    "BrowserLimits",
    "BrowserNavigateRequest",
    "BrowserObservation",
    "BrowserOpenSessionRequest",
    "BrowserPage",
    "BrowserPageRef",
    "BrowserPageSnapshot",
    "BrowserPageStatus",
    "BrowserPermissionError",
    "BrowserPressKeyRequest",
    "BrowserProvider",
    "BrowserProviderError",
    "BrowserProviderUnavailableError",
    "BrowserReadyState",
    "BrowserRecoveryAction",
    "BrowserRecoveryPolicy",
    "BrowserRecoveryResult",
    "BrowserRuntime",
    "BrowserScreenshotMetadata",
    "BrowserSelectRequest",
    "BrowserSession",
    "BrowserSessionStatus",
    "BrowserTimeoutError",
    "BrowserValidationError",
    "BrowserVerificationResult",
    "BrowserVerificationStatus",
    "BrowserWaitRequest",
    "BrowserWaitState",
    "BrowserWaitUntil",
    "CalculatorTool",
    "Capability",
    "ChatMessage",
    "CodeAnalysisLimitReason",
    "CodeAnalysisMethod",
    "CodeAnalysisRequest",
    "CodeAnalysisResult",
    "CodeAnalysisStatus",
    "CodeChange",
    "CodeDiagnostic",
    "CodeDiagnosticBatch",
    "CodeDiagnosticCategory",
    "CodeDiagnosticsEngine",
    "CodeEditRequest",
    "CodeEditResult",
    "CodeEditStatus",
    "CodeFile",
    "CodeFileMetric",
    "CodeLanguage",
    "CodePatch",
    "CodeRegion",
    "CodeSkipReason",
    "CodeSymbol",
    "CodeSymbolKind",
    "CodeTestPlanRequest",
    "CodeTestPlanResult",
    "CodeTestPlanStatus",
    "CodingAnalysisRuntime",
    "CodingError",
    "CodingLimitError",
    "CodingLimits",
    "CodingObservation",
    "CodingOperation",
    "CodingPermissionError",
    "CodingProject",
    "CodingProvider",
    "CodingProviderError",
    "CodingTimeoutError",
    "CodingUnsupportedOperationError",
    "CodingValidationError",
    "CodingWorkspaceError",
    "ComparisonLimitError",
    "ComputerActionResult",
    "ComputerActionStatus",
    "ComputerActiveWindowTool",
    "ComputerClickTool",
    "ComputerCursorPositionTool",
    "ComputerDoubleClickTool",
    "ComputerError",
    "ComputerFocusWindowTool",
    "ComputerHotkeyTool",
    "ComputerInspectUITool",
    "ComputerLimits",
    "ComputerListWindowsTool",
    "ComputerMoveMouseTool",
    "ComputerObservation",
    "ComputerOperationResult",
    "ComputerPressKeyTool",
    "ComputerProvider",
    "ComputerProviderError",
    "ComputerRuntime",
    "ComputerScreenInfoTool",
    "ComputerScreenshotTool",
    "ComputerSelectUIElementTool",
    "ComputerTypeTextTool",
    "ComputerValidationError",
    "Context",
    "ContextBuilder",
    "ContextItem",
    "ContextRequest",
    "CopyFileTool",
    "CreateDirectoryTool",
    "DateTimeTool",
    "DeleteFileTool",
    "DemoTool",
    "DeterministicVisionProvider",
    "DiagnosticSeverity",
    "Document",
    "DocumentChunk",
    "DocumentError",
    "DocumentLimits",
    "DocumentSection",
    "EventBus",
    "EventType",
    "Executor",
    "ExtractDocumentTool",
    "FileInfoTool",
    "FocusWindowAction",
    "ForgetTool",
    "ImageLimitError",
    "ImageSize",
    "InMemoryMemoryStore",
    "IndexDocumentTool",
    "InspectDocumentTool",
    "InvalidImageError",
    "InvalidRegionError",
    "JsonUtilsTool",
    "KeyboardAction",
    "KeyboardActionKind",
    "KeyboardKey",
    "KeyboardModifier",
    "KnowledgeStore",
    "LexicalMemoryRetriever",
    "ListDirectoryTool",
    "ListMemoriesTool",
    "Memory",
    "MemoryLimits",
    "MemoryRetriever",
    "MemoryStore",
    "MemoryStoreError",
    "MemoryType",
    "MockBrowserProvider",
    "MockCodingProvider",
    "MockElementDefinition",
    "MockModelProvider",
    "MockSTTProvider",
    "MockTTSProvider",
    "ModelGateway",
    "ModelPlanner",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "MouseAction",
    "MouseActionKind",
    "MouseButton",
    "MoveFileTool",
    "ObservedCodeFile",
    "OpenAIProvider",
    "OptionalImageSupportError",
    "PatchCheckStatus",
    "PatchValidationCheck",
    "PatchValidationMetadata",
    "PatchValidationStatus",
    "PermissionDecision",
    "PermissionDeniedError",
    "PermissionLevel",
    "PermissionManager",
    "PermissionPolicy",
    "Plan",
    "PlanStep",
    "Planner",
    "PlanningError",
    "PlaywrightBrowserProvider",
    "Point",
    "ProviderConfigurationError",
    "ProviderError",
    "ProviderUnavailableError",
    "ReadTextFileTool",
    "RecallTool",
    "RecoveryAction",
    "RecoveryPolicy",
    "RecoveryRecommendation",
    "RegionSource",
    "RememberTool",
    "RetrievalIndex",
    "SQLiteMemoryStore",
    "STTProvider",
    "ScreenInfo",
    "ScreenshotObservation",
    "SearchDocumentsTool",
    "SearchFilesTool",
    "SelectUIElementAction",
    "Settings",
    "SkippedCodeFile",
    "SourceCategory",
    "StepStatus",
    "SynthesisRequest",
    "SynthesisResult",
    "TTSProvider",
    "Task",
    "TaskState",
    "TaskStateError",
    "TaskStep",
    "TestCasePlan",
    "TextUtilsTool",
    "Tool",
    "ToolAlreadyRegisteredError",
    "ToolDescriptor",
    "ToolExecutionError",
    "ToolInputError",
    "ToolInvocation",
    "ToolNotFoundError",
    "ToolRegistry",
    "ToolResult",
    "ToolRuntime",
    "ToolSpec",
    "TranscriptionResult",
    "TranscriptionStatus",
    "TransientProviderError",
    "UIElement",
    "UnsupportedPlatformError",
    "UpdateMemoryTool",
    "VerificationCondition",
    "VerificationKind",
    "VerificationResult",
    "VerificationStatus",
    "Verifier",
    "VerifyResult",
    "VisionAnalyzeScreenshotTool",
    "VisionComparisonError",
    "VisionError",
    "VisionLimits",
    "VisionProvider",
    "VisionProviderError",
    "VisionRuntime",
    "VisionTimeoutError",
    "VisualAnalysis",
    "VisualMatch",
    "VisualMatchStatus",
    "VisualObservation",
    "VisualRegion",
    "VisualVerificationCondition",
    "VisualVerificationKind",
    "VisualVerificationResult",
    "VisualVerificationStatus",
    "VisualVerifier",
    "VoiceError",
    "VoiceLimitError",
    "VoiceLimits",
    "VoiceNormalizeTool",
    "VoiceObservation",
    "VoiceProviderError",
    "VoiceResponse",
    "VoiceResponseStatus",
    "VoiceRuntime",
    "VoiceTimeoutError",
    "VoiceValidationError",
    "WindowInfo",
    "WindowsComputerProvider",
    "Workspace",
    "WorkspaceError",
    "WorkspaceLimits",
    "WriteTextFileTool",
    "bounded_text",
    "bounded_value",
    "build_gateway",
    "classify_computer_operation",
    "create_provider",
    "make_memory_id",
    "metadata_size_bytes",
    "normalize_transcription_text",
    "plan_json_schema",
    "register_browser_tools",
    "register_computer_tools",
    "register_default_tools",
    "register_document_tools",
    "register_memory_tools",
    "register_vision_tools",
    "register_voice_tools",
    "register_workspace_tools",
    "utc_now",
    "validate_against_schema",
    "verify_condition",
]

from .media import (
    ImageGenerationProvider,
    LocalImageGenerator,
    LocalVideoRenderer,
    MediaAsset,
    MediaError,
    MediaFormat,
    MediaKind,
    MediaLimits,
    MediaProviderError,
    MediaRequest,
    MediaResult,
    MediaValidationError,
    VideoGenerationProvider,
    VideoRequest,
    VideoScene,
)
from .task_manager import TaskManager, TaskStore
